classDiagram

	class CrashDriverInfo{
	}

	CrashDriverInfo o-- Driver
	CrashDriverInfo o-- InjuredPerson
	CrashDriverInfo o-- Crash
	CrashDriverInfo o-- Charge

	Person <|-- Driver
	Person <|-- InjuredPerson
	
	class Person{
		+Date BirthDate
		+String BirthDatePrivacyCode
		+String FirstName
		+String MiddleName
		+String LastName
	}
	
	class Driver{
		+String DriverLicenseNumber
		+String Email
	
	}

	class InjuredPerson{
		+String InjuryDescription
		+Code SeverityCode
		+String InjuryPrivacyCode
		+Boolean ThroughWindow
	}

	class Charge{
		+String Description
		+boolean isFelony
	}

	class Crash{
		+Date CrashDate
		+String CrashLocationCoordinates
	}

	Person <--> Charge
