classDiagram

	class CrashDriverInfo{
	}

	CrashDriverInfo o-- Person
	CrashDriverInfo o-- Crash
	CrashDriverInfo o-- PersonChargeAssociation
	CrashDriverInfo o-- Charge
	CrashDriverInfo o-- Metadata
	CrashDriverInfo o-- PrivacyMetadata
	

	class Person{
	}

	Person o-- PersonName
	Person o-- PersonBirthDate

	class PersonName{
		+String PersonGivenName
		+String PersonMiddleName
		+String PersonLastName
	}

	class PersonBirthDate{
		+Date Date
	}

	class PersonChargeAssociation{
		+Boolean JuvenileAsAdultIndicator
	}
	PersonChargeAssociation o-- Person
	PersonChargeAssociation o-- Charge
	
	class Charge{
		+String ChargeDescriptionText
		+Boolean ChargeFelonyIndicator
	}
	
	class Metadata{
		+Boolean CriminalInformationIndicator
	}
	
	class PrivacyMetadata{
		+String PrivacyCode
	}

	Activity <|-- Incident
	Incident <|-- Crash

	Activity o-- ActivityDate

	class Crash{
	}
	
	Crash o-- CrashVehicle
	CrashVehicle o-- CrashDriver
	Crash o-- CrashPerson
	CrashPerson o-- CrashPersonInjury
	CrashPerson o-- Person
	Crash o-- Location
	CrashDriver o-- Person
	CrashDriver o-- DriverLicense
	DriverLicense o-- DriverLicenseCardIdentification
	
	
	class CrashDriver{
	}

	class CrashPerson{
		+Boolean PersonDefenestrationIndicator
	}
	class CrashPersonInjury{
		+String InjuryDescriptionText
		+String InjurySeverityCode
	}
	
	class Incident{
	}
	
	class Activity{
	}

	class ActivityDate{
		+Date Date
	}

	class DriverLicense{
	}
	
	class DriverLicenseCardIdentification{
		+String IdentificationID
	}

	class ContactInformation{
		+String ContactEmailID
	}

	DriverLicenseCardIdentification o-- ContactInformation

	Location o-- Location2DGeospatialCoordinate
	Location2DGeospatialCoordinate o-- GeographicCoordinateLatitude
	Location2DGeospatialCoordinate o-- GeographicCoordinateLongitude
	
	Location o-- LocationGeospatialPoint
	LocationGeospatialPoint o-- Point
	Point <-- pos
	
	class Location{
		
	}

	class Location2DGeospatialCoordinate{
	}

	class GeographicCoordinateLatitude{
		+Number LatitudeDegreeValue
		+Number LatitudeMinuteValue
	}

	class GeographicCoordinateLongitude{
		+Number LongitudeDegreeValue
		+Number LongitudeMinuteValue
	}

	class LocationGeospatialPoint{
	}
	
	class Point{
		+String id
	}
	
	class pos{
		+String srsName
		+String Value
	}
