sequenceDiagram
	Agreement to Share ->> Source Documents: Scenario Planning
	Source Documents ->> Diagrams: Requirement Analysis
	Diagrams ->> Mapping Spreadsheet: Mapping
	Mapping Spreadsheet ->> Schemas: Creating and Validating Schemas
	Schemas ->> IEPD Package: Assembly
	IEPD Package ->> Repository Record: Publishing
